project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Community Schools Retention Study"
  search:
    location: sidebar
    type: textbox
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - sidebar:reports
      
    background: "#2774AE"
    right:
    - icon: github
      menu:
        - text: Source Code
          url: https://github.com/yjeffrey77/cs_teach_rent2

  sidebar:
    - id: reports
      title: "Reports"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
       - y3_data/01_run_descriptives.qmd
       - y3_data/03_report_full.qmd
       - y3_data/04_neighborhood_report.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
