project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Community Schools Retention Study"
  search:
    location: sidebar
    type: textbox
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - sidebar:reports
      
    background: "#2774AE"
    right:
    - icon: github
      menu:
        - text: Source Code
          url: https://github.com/yjeffrey77/cs_teach_rent2

  sidebar:
    
    - title: "Home"
      contents: 
       - index.qmd
       - y3_data/01_run_descriptives.qmd
       - y3_data/03_report_full.qmd
       - y3_data/04_neighborhood_report.qmd
       - y3_data/05_school_analysis.qmd
       - y3_data/06_teacher_veteran_status.qmd
       - y3_data/07_test_results.qmd
       - y3_data/08_cs_only_schools.qmd
       # navigation items

    - id: reports
      title: "Reports"
      contents: 
       - y3_data/01_run_descriptives.qmd
       - y3_data/03_report_full.qmd
       - y3_data/04_neighborhood_report.qmd
       - y3_data/05_school_analysis.qmd
       - y3_data/06_teacher_veteran_status.qmd
       - y3_data/07_test_results.qmd
       - y3_data/08_cs_only_schools.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
