---
title: "Test Results"
execute:
  echo: false
  message: false
  warning: false
format: 
  html:
    embed-resources: true
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false

## Housekeeping

## ---------------------------
## libraries
## ---------------------------
library(tidyverse)
library(readxl)
library(openxlsx)
library(janitor)
library(kableExtra)
library(pwr)
library(kableExtra)
library(knitr)

## ---------------------------
## directory paths
## ---------------------------

#see current directory
#getwd()

#set current directory
code_file_dir<-file.path("C:/Users/yjeff/Desktop/Community Schools/Teacher Retention Data",
                "Analyses","cs_teach_rent2",  "y3_data")

data_file_dir<-file.path("C:/Users/yjeff/Box/LAUSD TR Data Year 3")

## ---------------------------
## helper functions
## ---------------------------

update_tbl_names<-function(df){
  df_update<-df
  colnames(df_update)<-c("School", "2019", "2020", "2021", "2022", "2023")
  return(df_update)
}

## ---------------------------
## load & inspect data
## ---------------------------

# load(file.path(code_file_dir, "rent_tbls.RData"))
# load(file.path(code_file_dir, "rent_plots.RData"))

#toc tables
# load(file.path(code_file_dir, "toc_rent_tbls.RData"))
# load(file.path(code_file_dir, "rent_plots_toc.RData"))

load(file.path(code_file_dir, "test_tbls.RData"))


## Add Lists
source(file.path(code_file_dir, "00_school_lists.R"))


```


## Purpose

The purpose of this document is to show the test results comparing Community Schools with their Traditional Public Schools.

## T-Test Results

<details>

```{r, echo = FALSE, results='asis'}

combined_t_test %>% kable()

```

</details>
