---
title: "Year 1 to Year 3 - Report"
execute:
  echo: false
  message: false
  warning: false
format: 
  html:
    embed-resources: false
editor: visual
---

## Purpose

Provides plots and tables for the Y1 to Y3 report.

```{r}
#| echo: false
#| message: false
#| warning: false

## Housekeeping

## ---------------------------
## libraries
## ---------------------------
library(tidyverse)
library(kableExtra)
library(pwr)
library(knitr)

## ---------------------------
## directory paths
## ---------------------------

#see current directory
#getwd()

#set current directory
code_file_dir<-file.path("C:/Users/yjeff/Desktop/Community Schools/Teacher Retention Data","Analyses", "cs_teach_rent2","y3_data")

data_file_dir<-file.path("C:/Users/yjeff/Box/LAUSD TR Data Year 3")

## ---------------------------
## helper functions
## ---------------------------

## ---------------------------
## load & inspect data
## ---------------------------

load(file.path(code_file_dir, "y1_y3_plots_and_tbls.RData"))

## Add Lists
source(file.path(code_file_dir, "00_school_lists.R"))
```

# Descriptive Analyses - Retention Rates

## Schools 

```{r, echo = FALSE, results='asis'}
teach_yr_string<-names(combined_rent_tbls)

gxs<-lapply(1:1, function(x){
  
  teach_year <- teach_yr_string[[x]]
  rent_tbl<-combined_rent_tbls
  rent_plots<-y1_y3_plots

  knit_child(
    '_08_y1_y3_report - child.Rmd', envir = environment(), quiet = TRUE
    
  )
})

cat(unlist(gxs), sep = '\n')

```

## Schools Masked Version

```{r, echo = FALSE, results='asis'}
teach_yr_string<-names(combined_rent_tbls)

gxs<-lapply(1:1, function(x){
  
  teach_year <- teach_yr_string[[x]]
  rent_tbl<-combined_rent_tbls_v2
  rent_plots<-y1_y3_plots_v2

  knit_child(
    '_08_y1_y3_report - child.Rmd', envir = environment(), quiet = TRUE
    
  )
})

cat(unlist(gxs), sep = '\n')

```

